--drop table keywords;
--drop table users;
--drop table sent;
--TODO: таки мб переедем на Flyway?
CREATE TABLE IF NOT EXISTS users(
id bigint PRIMARY KEY,
first_name VARCHAR(100),
last_name VARCHAR(100),
user_name VARCHAR(100),
code VARCHAR(100),
token VARCHAR(250),
vk_id INTEGER,
registration_date TIMESTAMP);

CREATE TABLE IF NOT EXISTS keywords(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id bigint REFERENCES users(id),
word VARCHAR(250) NOT NULL);

--TODO: некорректное название таблицы
CREATE TABLE IF NOT EXISTS sent(
sent_news_data VARCHAR(250) PRIMARY KEY,
user_id bigint REFERENCES users(id));