drop table keywords;
drop table users;


CREATE TABLE IF NOT EXISTS users(
id LONG PRIMARY KEY,
first_name VARCHAR(100),
last_name VARCHAR(100),
user_name VARCHAR(100),
code VARCHAR(100),
token VARCHAR(250),
vk_id INTEGER,
registration_date TIMESTAMP);

CREATE TABLE IF NOT EXISTS keywords(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id LONG REFERENCES users(id),
word VARCHAR(250) NOT NULL);